apiVersion: v1
kind: Pod
metadata:
  name: datadog-java-apm-demo
  annotations:
    admission.datadoghq.com/java-lib.version: "latest"
  labels:
    admission.datadoghq.com/enabled: "true"
spec:
  containers:
  - name: java-service
    image: nilushancosta/datadog-java-apm-demo
    ports:
    - containerPort: 8080